// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP_cGcrml2OAiaAaespZbKf2ScrInfdbw',
    appId: '1:35186220381:web:204fff274f87219e4b1cb4',
    messagingSenderId: '35186220381',
    projectId: 'pickpay-49b45',
    authDomain: 'pickpay-49b45.firebaseapp.com',
    storageBucket: 'pickpay-49b45.firebasestorage.app',
    measurementId: 'G-6WK1K2RNS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlOOt3kAYqF7qda9J582J1vGfsr5sjNKI',
    appId: '1:35186220381:android:c7618ae2ddc4c7ac4b1cb4',
    messagingSenderId: '35186220381',
    projectId: 'pickpay-49b45',
    storageBucket: 'pickpay-49b45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7KCAqEPKyVlZLAJreLtkzV-CN9h1w2AA',
    appId: '1:35186220381:ios:933e6aa48aeb3a744b1cb4',
    messagingSenderId: '35186220381',
    projectId: 'pickpay-49b45',
    storageBucket: 'pickpay-49b45.firebasestorage.app',
    androidClientId: '35186220381-tne371f0l5unf1tjg7oro7bob9i9ubfk.apps.googleusercontent.com',
    iosClientId: '35186220381-gadi5lmm8vd2647cg9cgs1nct2lfk1g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7KCAqEPKyVlZLAJreLtkzV-CN9h1w2AA',
    appId: '1:35186220381:ios:933e6aa48aeb3a744b1cb4',
    messagingSenderId: '35186220381',
    projectId: 'pickpay-49b45',
    storageBucket: 'pickpay-49b45.firebasestorage.app',
    androidClientId: '35186220381-tne371f0l5unf1tjg7oro7bob9i9ubfk.apps.googleusercontent.com',
    iosClientId: '35186220381-gadi5lmm8vd2647cg9cgs1nct2lfk1g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP_cGcrml2OAiaAaespZbKf2ScrInfdbw',
    appId: '1:35186220381:web:53efefde78e538fa4b1cb4',
    messagingSenderId: '35186220381',
    projectId: 'pickpay-49b45',
    authDomain: 'pickpay-49b45.firebaseapp.com',
    storageBucket: 'pickpay-49b45.firebasestorage.app',
    measurementId: 'G-WTLF4QZ8L5',
  );

}